app:
    resource: '@AppBundle/Controller/'
    type: annotation
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }
login:
    path: /login
    defaults: { _controller: AppBundle:Auth:login}
login_check:
    path: /login_check
logout:
    path: /logout
